// Writes config.js from environment variables (Vercel) or the local .env file.
// The page reads window.TROUSSEAU_CONFIG and falls back to its built-in values
// when config.js is missing, so this step never breaks the site.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function readDotEnv(file) {
  if (!fs.existsSync(file)) return {};
  const vars = {};
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m) continue;
    vars[m[1]] = m[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return vars;
}

function jwtRole(key) {
  try {
    return JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString()).role;
  } catch (e) {
    return null;
  }
}

function writeConfig(config) {
  fs.writeFileSync(path.join(root, 'config.js'),
    `// Generated by scripts/build-config.js. Do not edit; change .env or the Vercel environment variables instead.\nwindow.TROUSSEAU_CONFIG = ${JSON.stringify(config, null, 2)};\n`);
}

const fileVars = readDotEnv(path.join(root, '.env'));
const url = process.env.SUPABASE_URL || fileVars.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || fileVars.SUPABASE_ANON_KEY || '';

if (!url || !key) {
  // Still write the file, so the page never requests a config.js that doesn't exist.
  writeConfig({});
  console.log('build-config: SUPABASE_URL or SUPABASE_ANON_KEY not set; wrote an empty config.js, so the page uses its built-in values.');
  process.exit(0);
}
if (!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(url)) {
  console.error(`build-config: SUPABASE_URL doesn't look like a Supabase project URL: ${url}`);
  process.exit(1);
}
if (jwtRole(key) === 'service_role') {
  console.error('build-config: SUPABASE_ANON_KEY is a service_role key. It would give every visitor full database access. Use the anon key.');
  process.exit(1);
}

const config = {supabaseUrl: url.replace(/\/$/, ''), supabaseAnonKey: key};
writeConfig(config);
console.log(`build-config: wrote config.js for ${config.supabaseUrl}`);
